name: Client CI

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn' # Кешуємо Yarn для швидшого білду

      - name: Install dependencies
        run: |
          cd сlient
          yarn install

      - name: Lint code
        run: |
          cd сlient
          yarn lint
          yarn lint:prettier
          yarn lint:style

      - name: Build Next.js app
        run: |
          cd сlient
          yarn build
