name: Client CI

on:
  push:
    paths:
      - "client/**"
  pull_request:
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Disable Yarn cache (optional, для перевірки)
        run: |
          yarn cache clean

      - name: Install pm2
        run: |
          npm install -g pm2

      - name: Install dependencies
        run: |
          cd client
          yarn install --frozen-lockfile  # Обов'язкове використання lockfile

        if: always()
      - name: Run tests
        run: |
          cd client
          yarn test:unit

        if: always()
      - name: Build Storybook
        run: |
          cd client
          yarn storybook:build

        if: always()
      - name: Start Storybook
        run: |
          cd client
          pm2 start yarn --name "storybook" -- storybook

        if: always()
      - name: Screenshot testing
        run: |
          cd client
          yarn test:ui:ci

        if: always()
      - name: Lint code
        run: |
          cd client
          yarn lint
          yarn lint:prettier
          yarn lint:style

      - name: Stop Storybook
        run: |
          pm2 stop "storybook"

        if: always()
      - name: Build Next.js app
        run: |
          cd client
          yarn build
