name: Server CI

on:
  workflow_dispatch:
  push:
    paths:
      - "server/**"
  pull_request:
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: |
          cd server
          yarn lint

      - name: Test
        run: |
          cd server
          yarn test:unit

      - name: Typecheck
        run: |
          cd server
          yarn typecheck

      - name: Build
        run: |
          cd server
          yarn build
